apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-fthn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-fthn
    app.kubernetes.io/part-of: tkrw-pr712-0075-0025-app
  name: devfile-sample-fthn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-fthn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-fthn
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0025-tenant/tkrw-pr712-0075-0025-app/devfile-sample-fthn@sha256:b39a3f2ee89bc828f033f350beb4f59f01a18835a2b27a84308306c8b964db65
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
